PRN221_ASSIGNMENT/Models/Schedule.cs
using System;
using System.Collections.Generic;

namespace PRN221_ASSIGNMENT.Models
{
    public partial class Schedule
    {
        public Schedule()
        {
            ScheduleDetails = new HashSet<ScheduleDetail>();
        }

        public int Id { get; set; }
        public int ClassId { get; set; }
        public int SubjectId { get; set; }
        public int TeacherId { get; set; }
        public int RoomId { get; set; }
        public int? SlotTemplateId { get; set; }

        public virtual GroupClass Class { get; set; } = null!;
        public virtual Room Room { get; set; } = null!;
        public virtual SlotTemplate? SlotTemplate { get; set; }
        public virtual Subject Subject { get; set; } = null!;
        public virtual Teacher Teacher { get; set; } = null!;
        public virtual ICollection<ScheduleDetail> ScheduleDetails { get; set; }
    }
}

PRN221_ASSIGNMENT/Pages/GroupClass/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PRN221_ASSIGNMENT.Models;

namespace PRN221_ASSIGNMENT.Pages.GroupClass
{
    public class EditModel : PageModel
    {
        private readonly PRN221_ASSIGNMENT.Models.ScheduleManagementContext _context;

        public EditModel(PRN221_ASSIGNMENT.Models.ScheduleManagementContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Models.GroupClass GroupClass { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.GroupClasses == null)
            {
                return NotFound();
            }

            var groupclass =  await _context.GroupClasses.FirstOrDefaultAsync(m => m.Id == id);
            if (groupclass == null)
            {
                return NotFound();
            }
            GroupClass = groupclass;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(GroupClass).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!GroupClassExists(GroupClass.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool GroupClassExists(int id)
        {
          return (_context.GroupClasses?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

PRN221_ASSIGNMENT/Pages/Room/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PRN221_ASSIGNMENT.Models;

namespace PRN221_ASSIGNMENT.Pages.Room
{
    public class EditModel : PageModel
    {
        private readonly PRN221_ASSIGNMENT.Models.ScheduleManagementContext _context;

        public EditModel(PRN221_ASSIGNMENT.Models.ScheduleManagementContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Models.Room Room { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Rooms == null)
            {
                return NotFound();
            }

            var room =  await _context.Rooms.FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }
            Room = room;
           ViewData["BuildingId"] = new SelectList(_context.Buildings, "Id", "Id");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Room).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!RoomExists(Room.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool RoomExists(int id)
        {
          return (_context.Rooms?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

PRN221_ASSIGNMENT/Pages/Schedule/AddCSV.cshtml.cs
using CsvHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PRN221_ASSIGNMENT.DTO;
using PRN221_ASSIGNMENT.Models;
using PRN221_ASSIGNMENT.Service;
using System.Globalization;

namespace PRN221_ASSIGNMENT.Pages.Schedule
{
    public class AddModel : PageModel
    {
        private ScheduleManagementContext _context;

        public AddModel(ScheduleManagementContext context)
        {
            _context = context;
        }

        public void OnGet()
        {
        }

        public async void OnPostImport(IFormFile csvFile)
        {
            ScheduleService service = new ScheduleService(_context);
            DataService dataService = new DataService(_context);
            if (csvFile != null && csvFile.Length > 0)
            {

                if (Path.GetExtension(csvFile.FileName).ToLower() != ".csv")
                {
                    ViewData["Messages"] = new List<string> { "Uploaded file is not a CSV file." };
                    return;
                }
                // Specify the path where you want to save the uploaded XML file
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads", csvFile.FileName);

                // Save the uploaded XML file to the specified path
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await csvFile.CopyToAsync(stream);
                }

                using (var streamReader = new StreamReader(filePath))
                {
                    using (var csvReader = new CsvReader(streamReader, CultureInfo.InvariantCulture))
                    {


                        var records = csvReader.GetRecords<CsvData>().ToList();
                        service.DeleteAllData();
                        List<string> messages = new List<string>();

                        foreach (var record in records)
                        {
                            // Check if the CSV record has all required fields
                            if (string.IsNullOrEmpty(record.Class) || string.IsNullOrEmpty(record.Subject) ||
                                string.IsNullOrEmpty(record.Room) || string.IsNullOrEmpty(record.Teacher) ||
                                string.IsNullOrEmpty(record.TimeSlot))
                            {
                                messages.Add("CSV file is missing one or more required fields.");
                                ViewData["Messages"] = messages;
                                return;
                            }

                            // Check if the CSV record has more fields than needed
                            if (record.GetType().GetProperties().Length > 5)
                            {
                                messages.Add("CSV file contains more fields than needed.");
                                ViewData["Messages"] = messages;
                                return;
                            }
                        }

                        for (int i = 0; i < records.Count(); i++)
                        {
                            string message = dataService.AddDataToDatabase(records[i]);
                            messages.Add($"Line {i + 1}: " + message);
                        }

                        ViewData["Messages"] = messages;
                    }
                }
            }
            else
            {
                ViewData["Messages"] = new List<string> { "No file uploaded." };
            }

        }

        public async void OnPostAdd(IFormFile csvFile)
        {
            DataService service = new DataService(_context);
            if (csvFile != null && csvFile.Length > 0)
            {

                if (Path.GetExtension(csvFile.FileName).ToLower() != ".csv")
                {
                    ViewData["Messages"] = new List<string> { "Uploaded file is not a CSV file." };
                    return;
                }
                // Specify the path where you want to save the uploaded XML file
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads", csvFile.FileName);

                // Save the uploaded XML file to the specified path
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await csvFile.CopyToAsync(stream);
                }

                using (var streamReader = new StreamReader(filePath))
                {
                    using (var csvReader = new CsvReader(streamReader, CultureInfo.InvariantCulture))
                    {
                        

                        var records = csvReader.GetRecords<CsvData>().ToList();
                        List<string> messages = new List<string>();

                        foreach (var record in records)
                        {
                            // Check if the CSV record has all required fields
                            if (string.IsNullOrEmpty(record.Class) || string.IsNullOrEmpty(record.Subject) ||
                                string.IsNullOrEmpty(record.Room) || string.IsNullOrEmpty(record.Teacher) ||
                                string.IsNullOrEmpty(record.TimeSlot))
                            {
                                messages.Add("CSV file is missing one or more required fields.");
                                ViewData["Messages"] = messages;
                                return;
                            }

                            // Check if the CSV record has more fields than needed
                            if (record.GetType().GetProperties().Length > 5)
                            {
                                messages.Add("CSV file contains more fields than needed.");
                                ViewData["Messages"] = messages;
                                return;
                            }
                        }

                        for (int i = 0; i < records.Count(); i++)
                        {
                            string message = service.AddDataToDatabase(records[i]);
                            messages.Add($"Line {i+1}: " + message);
                        }

                        ViewData["Messages"] = messages;
                    }
                }
            }
            else
            {
                ViewData["Messages"] = new List<string> { "No file uploaded." };
            }

        }
    }
}

PRN221_ASSIGNMENT/Pages/Schedule/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PRN221_ASSIGNMENT.Pages.Schedule
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

PRN221_ASSIGNMENT/Pages/Schedule/View.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PRN221_ASSIGNMENT.Models;
using PRN221_ASSIGNMENT.Service;

namespace PRN221_ASSIGNMENT.Pages.Schedule
{
    public class ViewModel : PageModel
    {
        private readonly ScheduleManagementContext _context;

        public ViewModel(ScheduleManagementContext context)
        {
            _context = context;
        }

        [BindProperty]
        public int ScheduleId { get; set; }

        public List<Models.Schedule> Schedules { get; set; }

        public List<Models.Teacher> Teachers {  get; set; }
        
        public List<Models.GroupClass> Classes { get; set; }

        public List<Models.SlotTemplate> Slots { get; set; }

        [BindProperty]
        public int SelectedTeacher {  get; set; }

        [BindProperty]
        public int SelectedClass { get; set; }

        [BindProperty]
        public int SelectedSlot { get; set; }

        [BindProperty]
        public int Page {  get; set; }

        public int TotalPages { get; set; }
        public void OnGet()
        {
            Page = 1;
            GetData();
        }

        private void GetData()
        {
            Classes = _context.GroupClasses.ToList();
            Teachers = _context.Teachers.ToList();
            Slots = _context.SlotTemplates.ToList();
            Schedules = _context.Schedules.Include(s => s.Class).Include(s => s.Room)
                                            .ThenInclude(r => r.Building).Include(s => s.Teacher)
                                            .Include(s => s.Subject).Include(s => s.SlotTemplate)
                                            .ToList();
            if(SelectedTeacher != 0 && SelectedTeacher != null)
            {
                Schedules = Schedules.Where(s => s.TeacherId == SelectedTeacher).ToList();
            }
            if (SelectedClass != 0 && SelectedClass != null)
            {
                Schedules = Schedules.Where(s => s.ClassId == SelectedClass).ToList();
            }
            if (SelectedSlot != 0 && SelectedSlot != null)
            {
                Schedules = Schedules.Where(s => s.SlotTemplateId == SelectedSlot).ToList();
            }

            var pageSize = 10;

            TotalPages = (int)Math.Ceiling(Schedules.Count() / (double)pageSize);
            Schedules = Schedules.Skip((Page - 1) * pageSize).Take(pageSize).ToList();
        }

        public void OnPostDelete()
        {
            ScheduleService service = new ScheduleService(_context);
            service.DeleteScheduleById(ScheduleId);
            GetData();
        }

        public void OnPostFilter()
        {
            GetData();
        }

        public void OnPostPaging()
        {
            GetData();
        }
    }
}

PRN221_ASSIGNMENT/Pages/Schedule/ViewTimetable.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PRN221_ASSIGNMENT.DTO;
using PRN221_ASSIGNMENT.Models;
using PRN221_ASSIGNMENT.Service;

namespace PRN221_ASSIGNMENT.Pages.Schedule
{
    public class ViewTimetableModel : PageModel
    {
        private ScheduleManagementContext _context;
        public ViewTimetableModel(ScheduleManagementContext context)
        {
            _context = context;
        }

        public List<WeekDTO> Weeks { get; set; }

        public List<DateTime> Days { get; set; }

        [BindProperty]
        public int WeekNumber { get; set; }

        [BindProperty]
        public int SelectedClass { get; set; }

        [BindProperty]
        public int SelectedTeacher { get; set; }

        public List<ScheduleDetail>[,] ScheduleList { get; set; }

        public List<Models.GroupClass> Classes { get; set; }
        public List<Models.Teacher> Teachers { get; set; }
        public void OnGet()
        {
            WeekNumber = 1;
            GetData();
        }

        private void GetData()
        {
            ScheduleDetailService scheduleDetailService = new ScheduleDetailService(_context);
            SlotService slotService = new SlotService(_context);

            ScheduleList = new List<ScheduleDetail>[12, 7];
            Weeks = slotService.FindWeekList();
            Classes = _context.GroupClasses.ToList();
            Teachers = _context.Teachers.ToList();
            
            var currentWeek = Weeks.FirstOrDefault(w => w.WeekNo == WeekNumber);
            Days = slotService.GetDaysBetween(currentWeek);
            List<ScheduleDetail> ScheduleInWeek = scheduleDetailService.FindScheduleDetailInWeek(currentWeek);

            if(SelectedClass != null && SelectedClass != 0)
            {
                ScheduleInWeek = ScheduleInWeek.Where(s => s.Schedule.ClassId == SelectedClass).ToList();
            }
            if (SelectedTeacher != null && SelectedTeacher != 0)
            {
                ScheduleInWeek = ScheduleInWeek.Where(s => s.Schedule.TeacherId == SelectedTeacher).ToList();
            }
            for (int i = 0; i < 12; i++)
            {
                var slotId = i + 1;
                for(int j = 0; j < 7; j++)
                {
                    DateTime date = slotService.FindDateBasedOnWeek(currentWeek, j);
                    ScheduleList[i,j] = ScheduleInWeek.Where(s => s.SlotId == slotId && s.Date == date).ToList();
                }
            }
        }

        public void OnPostFilter()
        {
            GetData();
        }

        public void OnPostClear()
        {
            WeekNumber = 1;
            SelectedClass = 0;
            SelectedTeacher = 0;
            GetData();
        }
    }
}

PRN221_ASSIGNMENT/Pages/Schedule/AddCSV.cshtml
@page
@model PRN221_ASSIGNMENT.Pages.Schedule.AddModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
}
<style>
    a {
        text-decoration: none;
    }

    h2 {
        color: darkslateblue;
    }

    .container-form {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
    }

    .forms {
        display: flex;
    }

        .forms > div {
            margin-right: 40px;
            margin-left: 40px;
        }

    .result {
        margin-top: 20px;
        border: 2px solid #ccc;
        border-radius: 5px;
        padding: 10px;
        background-color: #f9f9f9;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        width: 400px; /* Adjust width as needed */
    }

        .result h2 {
            color: darkred;
            font-size: 20px;
            margin-bottom: 10px;
        }

        .result ul {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }

        .result li {
            color: red;
            margin-bottom: 5px;
        }

            .result li:first-child {
                margin-top: 5px;
            }

            .result li:last-child {
                margin-bottom: 0;
            }

            .result li.success {
                color: forestgreen;
            }

    .back-button{
        padding: 8px 16px;
        background-color: #3498db; /* Green */
        color: black;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        text-decoration: none; /* Remove underlines from links */
    }

    .back-button a {
        text-decoration: none;
        color:black
    }

        /* Styles for the button on hover */
        .back-button :hover {
            background-color: #2980b9; /* Darker green */
        }
</style>

<button class="back-button">
    <a href="/Schedule">Back</a>
</button>


<div class="container-form">
    <div class="forms">
        <div>
            <h2>Import full schedule from CSV:</h2>
            <p style="color:darkred">This will delete all the data existed in Schedule table</p>
            <form method="post" enctype="multipart/form-data" asp-page-handler="Import">
                <input type="file" name="csvFile" />
                <br />
                <input type="submit" value="Import" />
            </form>
        </div>
        <div>
            <h2>Add from CSV:</h2>
            <p style="color:darkred">Add data in Schedule table</p>
            <form method="post" enctype="multipart/form-data" asp-page-handler="Add">
                <input type="file" name="csvFile" />
                <br />
                <input type="submit" value="Add" />
            </form>
        </div>
    </div>

    <div class="result">
        @if (ViewData["Messages"] != null)
        {
            <h2>Results:</h2>
            <ul>
                @foreach (var message in (List<string>)ViewData["Messages"])
                {
                    @if (message.Contains("Saved successfully!"))
                    {
                        <li style="color:forestgreen">@message</li>
                    }
                    else
                    {
                        <li style="color:red">@message</li>
                    }
                }
            </ul>
        }
    </div>
</div>

PRN221_ASSIGNMENT/Pages/Schedule/Index.cshtml
@page
@model PRN221_ASSIGNMENT.Pages.Schedule.IndexModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
}

<style>
    .admin {
        text-align: center;
        margin-bottom: 20px;
    }

    h2 {
        color: darkslateblue;
        margin-bottom: 10px;
    }

    .link {
        display: inline-block;
        padding: 10px 20px;
        margin: 0 10px;
        color: #333;
        text-decoration: none;
        border: 2px solid #333;
        border-radius: 5px;
        transition: background-color 0.3s, color 0.3s;
    }

        .link:hover {
            background-color: #333;
            color: #fff;
        }
</style>


<div class="admin">
    <h2 style="text-align:center">Schedule Management</h2>
    <a class="link" href="/Schedule/AddCSV" style="">Import by CSV</a>
    <a class="link" href="/Schedule/View" style="">Manage Schedule</a>
</div>

PRN221_ASSIGNMENT/Pages/Schedule/View.cshtml
@page
@model PRN221_ASSIGNMENT.Pages.Schedule.ViewModel
@{
}

<style>
    .schedule-table {
        border-collapse: collapse;
        width: 100%;
    }
    a{
        text-decoration: none;
        color: black;
        
    }
        .schedule-table th, .schedule-table td {
            border: 1px solid black;
            padding: 8px;
            text-align: left;
        }

        .schedule-table th {
            background-color: #f2f2f2;
        }

        .schedule-table td .btn-container {
            display: flex;
        }

            .schedule-table td .btn-container button {
                margin-right: 5px;
            }

    .button-container {
        display: flex;
        justify-content: flex-end;
        margin-bottom: 10px; /* Adjust as needed */
    }

    .btn1-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100%;
    }

    .add-button {
        margin-left: 10px; /* Adjust as needed */
    }

        /* Styles for the button */
        .button-container button {
            padding: 8px 16px;
        background-color: #3498db; /* Green */
            
            border: none;
            border-radius: 4px;
            cursor: pointer;
            text-decoration: none; /* Remove underlines from links */
        }

            /* Styles for the button on hover */
        .button-container button:hover {
            background-color: #2980b9; /* Darker green */
            }

    .btn-container button {
        padding: 8px 16px;
        background-color: #3498db; /* Green */
        color: black;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        text-decoration: none; /* Remove underlines from links */
    }

        /* Styles for the button on hover */
        .btn-container button:hover {
            background-color: #2980b9; /* Darker green */
        }

        h1{
            text-align:center
        }

        .small-td{
            width:300px
        }

    .page-button {
        padding: 8px 12px;
        background-color: #f5f5f5;
        border: 1px solid #ccc;
        border-radius: 4px;
        color: #333;
        cursor: pointer;
        margin-right: 5px;
    }

        /* Active button style */
        .page-button.active {
            background-color: #007bff;
            color: #fff;
            border-color: #007bff;
        }

    .centered-form {
        display: flex;
        justify-content: center;
        margin-top: 10px;
    }
</style>

<div>
    <div class="btn-container">
        <button class="btn-container">
            <a href="/Schedule/">Back</a>
        </button>
    </div>
    
    <h1>Schedule List</h1>
    <div class="button-container">
        <button class="add-button">
            <a href="/Schedule/AddManually">Add</a>
        </button>
    </div>
    <form id="filterForm" method="post" asp-page-handler="filter" style="margin-bottom:10px">
        <input type="hidden" value="@Model.Page" asp-for="Page" />
        <label>Class:</label>
        <select id="classSelect" asp-for="SelectedClass">
            <option value="0">All Classes</option>
            @foreach (var c in Model.Classes)
            {
                <option value="@c.Id">@c.Code</option>
            }
        </select>
        <label>Teacher:</label>
        <select id="teacherSelect" asp-for="SelectedTeacher">
            <option value="0">All Teachers</option>
            @foreach (var t in Model.Teachers)
            {
                <option value="@t.Id">@t.Code</option>
            }
        </select>
        <label>Slot:</label>

        <select id="slotSelect" asp-for="SelectedSlot">
            <option value="0">All Slots</option>
            @foreach (var t in Model.Slots)
            {
                <option value="@t.Id">@t.Code</option>
            }
        </select>
    </form>

    
    <table class="schedule-table">
        <tr>
            <th>ScheduleId</th>
            <th>Class</th>
            <th>Subject</th>
            <th>Teacher</th>
            <th>Room</th>
            <th>Slot</th>
            <th></th>
        </tr>
        @foreach (var p in Model.Schedules)
        {
            <tr>
                <td>@p.Id</td>
                <td>@p.Class.Code</td>
                <td>@p.Subject.Code</td>
                <td>@p.Teacher.Code</td>
                <td>@(p.Room?.Building?.Code + "-" + p.Room?.Code)</td>
                <td>@p.SlotTemplate?.Code</td>
                <td class="small-td">
                    <div class="btn-container btn1-container">
                        <button>
                            <a href="/Schedule/ViewDetail?id=@p.Id">View Detail</a>
                        </button>
                        <button>
                            <a href="/Schedule/Edit?id=@p.Id">Edit</a>
                        </button>
                        <form method="post" asp-page-handler="delete">
                            <input type="hidden" value="@Model.SelectedClass" asp-for="SelectedClass" />
                            <input type="hidden" value="@Model.SelectedTeacher" asp-for="SelectedTeacher" />
                            <input type="hidden" value="@Model.SelectedSlot" asp-for="SelectedSlot" />
                            <input type="hidden" value="@Model.Page" asp-for="Page"/>
                            <button type="submit" name="ScheduleId" value="@p.Id">Delete</button>
                        </form>
                    </div>
                </td>
            </tr>
        }
    </table>
    @if(Model.TotalPages > 1)
    {
        <div class="centered-form">
            <form method="post" asp-page-handler="Paging">
                <input type="hidden" value="@Model.SelectedClass" asp-for="SelectedClass" />
                <input type="hidden" value="@Model.SelectedTeacher" asp-for="SelectedTeacher" />
                <input type="hidden" value="@Model.SelectedSlot" asp-for="SelectedSlot" />
                <button type="submit" name="Page" value="1" class="page-button">First</button>
                <button type="submit" name="Page" value="@Math.Max(Model.Page - 1, 1)" class="page-button">Previous</button>

                @for (int i = 1; i <= Model.TotalPages; i++)
                {
                    <button type="submit" name="Page" value="@i" class="page-button @(i == Model.Page ? "active" : "")">@i</button>
                }

                <button type="submit" name="Page" value="@Math.Min(Model.Page + 1, Model.TotalPages)" class="page-button">Next</button>
                <button type="submit" name="Page" value="@Model.TotalPages" class="page-button">Last</button>
            </form>
        </div>
    }
    

</div>

<script>
    // Get the form element
    var form = document.getElementById('filterForm');

    // Get the select elements
    var slotSelect = document.getElementById('slotSelect');
    var classSelect = document.getElementById('classSelect');
    var teacherSelect = document.getElementById('teacherSelect');

    // Add event listeners to the select elements
    slotSelect.addEventListener('change', function () {
        form.submit();
    });

    classSelect.addEventListener('change', function () {
        form.submit();
    });

    teacherSelect.addEventListener('change', function () {
        form.submit();
    });
</script>